{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Face Follower — Client V2 (MediaPipe)\n",
    "\n",
    "Reads the MJPEG stream from the ESP32-CAM, detects faces with **MediaPipe Face Detection (BlazeFace)**, chooses the largest/closest detected face, decides a direction, and sends it to the ESP32 `/motor` endpoint.\n",
    "\n",
    "This V2 keeps the original ESP32 HTTP API and motor logic. The main detection block is replaced with MediaPipe, with a small amount of temporal smoothing and command hysteresis to reduce LEFT/RIGHT jitter.\n",
    "\n",
    "**Before running:** set `ESP32_IP` below to the IP printed by the ESP32 Serial Monitor.\n",
    "\n",
    "**Important:** this notebook targets the legacy Python Face Detection API available in MediaPipe 0.10.21. That version supports Python 3.11 on Windows. It also uses `numpy<2` and `opencv-contrib-python<5` because MediaPipe 0.10.21 has a NumPy <2 compatibility requirement. After installing packages for the first time, restart the Jupyter kernel before continuing.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==================== INSTALL / IMPORT ====================\n",
    "# Run this cell once in a fresh environment.\n",
    "# After pip finishes, RESTART the Jupyter kernel, then run the import cell again.\n",
    "\n",
    "%pip install \"mediapipe==0.10.21\" \"numpy<2\" \"opencv-contrib-python<5\" requests\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import mediapipe as mp\n",
    "import numpy as np\n",
    "import requests\n",
    "import time\n",
    "import threading\n",
    "\n",
    "print(\"OpenCV:\", cv2.__version__)\n",
    "print(\"MediaPipe:\", mp.__version__)\n",
    "print(\"NumPy:\", np.__version__)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==================== CONFIG ====================\n",
    "ESP32_IP = \"10.158.116.178\"          # <-- change to your ESP32's actual IP\n",
    "STREAM_URL = f\"http://{ESP32_IP}:81/stream\"\n",
    "MOTOR_URL = f\"http://{ESP32_IP}/motor\"\n",
    "\n",
    "# Direction thresholds\n",
    "CENTER_DEADZONE = 0.15       # +-15% of frame width around center = forward\n",
    "CLOSE_FACE_RATIO = 0.35      # face width > 35% of frame width = stop\n",
    "\n",
    "# MediaPipe detection\n",
    "MIN_DETECTION_CONFIDENCE = 0.55\n",
    "MODEL_SELECTION = 0          # 0 = short range (best for a robot/person within ~2 m)\n",
    "MAX_NUM_FACES = 5\n",
    "\n",
    "# Temporal smoothing / command stability\n",
    "FACE_SMOOTHING_ALPHA = 0.35  # lower = smoother, higher = more responsive\n",
    "DIRECTION_CONFIRM_FRAMES = 2 # require same decision this many frames before changing command\n",
    "NO_FACE_STOP_FRAMES = 5\n",
    "COMMAND_COOLDOWN = 0.35      # minimum seconds between repeated HTTP commands\n",
    "\n",
    "# Video / display\n",
    "WINDOW_NAME = \"Face Follower V2 - MediaPipe\"\n",
    "# ==================================================\n",
    "\n",
    "mp_face_detection = mp.solutions.face_detection\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==================== MEDIAPIPE DETECTOR ====================\n",
    "# MediaPipe expects RGB input. It returns normalized bounding-box coordinates.\n",
    "\n",
    "face_detector = mp_face_detection.FaceDetection(\n",
    "    model_selection=MODEL_SELECTION,\n",
    "    min_detection_confidence=MIN_DETECTION_CONFIDENCE,\n",
    ")\n",
    "\n",
    "print(\"MediaPipe Face Detection ready.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==================== MOTOR COMMAND SENDER ====================\n",
    "# Same HTTP endpoint as the original notebook.\n",
    "# Requests run on a background thread so a slow ESP32 response does not freeze video processing.\n",
    "\n",
    "_last_sent_dir = None\n",
    "_last_sent_time = 0.0\n",
    "_command_lock = threading.Lock()\n",
    "\n",
    "\n",
    "def send_direction(direction: str):\n",
    "    \"\"\"Send a direction to the ESP32, but avoid unnecessary HTTP spam.\"\"\"\n",
    "    global _last_sent_dir, _last_sent_time\n",
    "\n",
    "    now = time.time()\n",
    "    with _command_lock:\n",
    "        if direction == _last_sent_dir and (now - _last_sent_time) < COMMAND_COOLDOWN:\n",
    "            return\n",
    "        _last_sent_dir = direction\n",
    "        _last_sent_time = now\n",
    "\n",
    "    def _worker():\n",
    "        try:\n",
    "            requests.get(\n",
    "                MOTOR_URL,\n",
    "                params={\"dir\": direction},\n",
    "                timeout=0.8,\n",
    "            )\n",
    "        except requests.RequestException as e:\n",
    "            print(f\"[motor] request failed: {e}\")\n",
    "\n",
    "    threading.Thread(target=_worker, daemon=True).start()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==================== FACE DETECTION HELPERS ====================\n",
    "def detection_to_box(detection, frame_w, frame_h):\n",
    "    \"\"\"Convert MediaPipe's normalized bounding box to (x, y, w, h) pixels.\"\"\"\n",
    "    bbox = detection.location_data.relative_bounding_box\n",
    "\n",
    "    x = int(bbox.xmin * frame_w)\n",
    "    y = int(bbox.ymin * frame_h)\n",
    "    w = int(bbox.width * frame_w)\n",
    "    h = int(bbox.height * frame_h)\n",
    "\n",
    "    # Clamp the box to the actual frame. MediaPipe boxes can extend slightly outside it.\n",
    "    x = max(0, min(x, frame_w - 1))\n",
    "    y = max(0, min(y, frame_h - 1))\n",
    "    w = max(1, min(w, frame_w - x))\n",
    "    h = max(1, min(h, frame_h - y))\n",
    "\n",
    "    return (x, y, w, h)\n",
    "\n",
    "\n",
    "def detection_score(detection):\n",
    "    \"\"\"Return MediaPipe's first/primary detection confidence.\"\"\"\n",
    "    scores = detection.score\n",
    "    return float(scores[0]) if scores else 0.0\n",
    "\n",
    "\n",
    "def choose_largest_face(detections, frame_w, frame_h):\n",
    "    \"\"\"Choose the largest detected face, matching the original notebook's behavior.\"\"\"\n",
    "    candidates = []\n",
    "    for detection in detections:\n",
    "        box = detection_to_box(detection, frame_w, frame_h)\n",
    "        x, y, w, h = box\n",
    "        area = w * h\n",
    "        candidates.append((area, detection_score(detection), box, detection))\n",
    "\n",
    "    if not candidates:\n",
    "        return None\n",
    "\n",
    "    # Largest area first; confidence breaks ties.\n",
    "    return max(candidates, key=lambda item: (item[0], item[1]))\n",
    "\n",
    "\n",
    "def smooth_box(previous_box, new_box, alpha=FACE_SMOOTHING_ALPHA):\n",
    "    \"\"\"Exponential moving average for a steadier face box.\"\"\"\n",
    "    if previous_box is None:\n",
    "        return new_box\n",
    "\n",
    "    old = np.array(previous_box, dtype=np.float32)\n",
    "    new = np.array(new_box, dtype=np.float32)\n",
    "    smoothed = (1.0 - alpha) * old + alpha * new\n",
    "    return tuple(int(v) for v in smoothed)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==================== DIRECTION LOGIC ====================\n",
    "def decide_direction(face_box, frame_w, frame_h):\n",
    "    \"\"\"face_box = (x, y, w, h) in pixels.\n",
    "    Returns one of: forward, left, right, stop.\n",
    "\n",
    "    This preserves the original notebook's rules:\n",
    "      - large face -> stop\n",
    "      - face left of deadzone -> left\n",
    "      - face right of deadzone -> right\n",
    "      - otherwise -> forward\n",
    "    \"\"\"\n",
    "    x, y, w, h = face_box\n",
    "    face_center_x = x + w / 2.0\n",
    "    frame_center_x = frame_w / 2.0\n",
    "    offset = (face_center_x - frame_center_x) / frame_w\n",
    "\n",
    "    face_width_ratio = w / frame_w\n",
    "\n",
    "    if face_width_ratio > CLOSE_FACE_RATIO:\n",
    "        return \"stop\"\n",
    "\n",
    "    if offset < -CENTER_DEADZONE:\n",
    "        return \"left\"\n",
    "    elif offset > CENTER_DEADZONE:\n",
    "        return \"right\"\n",
    "    else:\n",
    "        return \"forward\"\n",
    "\n",
    "\n",
    "def stabilize_direction(candidate):\n",
    "    \"\"\"Require a candidate command to persist for a few frames before switching.\"\"\"\n",
    "    global _pending_direction, _pending_count, _stable_direction\n",
    "\n",
    "    if candidate == _pending_direction:\n",
    "        _pending_count += 1\n",
    "    else:\n",
    "        _pending_direction = candidate\n",
    "        _pending_count = 1\n",
    "\n",
    "    if _pending_count >= DIRECTION_CONFIRM_FRAMES:\n",
    "        _stable_direction = candidate\n",
    "\n",
    "    return _stable_direction\n",
    "\n",
    "\n",
    "_pending_direction = None\n",
    "_pending_count = 0\n",
    "_stable_direction = \"stop\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==================== MAIN FACE FOLLOWER ====================\n",
    "def run_face_follower(show_window=True, max_seconds=None):\n",
    "    \"\"\"Main loop: stream -> MediaPipe -> smoothing -> direction -> ESP32.\n",
    "\n",
    "    Press 'q' in the video window to stop.\n",
    "    Set max_seconds for an automatic stop, useful for headless testing.\n",
    "    \"\"\"\n",
    "    cap = cv2.VideoCapture(STREAM_URL)\n",
    "    if not cap.isOpened():\n",
    "        print(f\"Could not open stream at {STREAM_URL}.\")\n",
    "        print(\"Check ESP32_IP, WiFi, and that the ESP32-CAM is powered on.\")\n",
    "        return\n",
    "\n",
    "    start_time = time.time()\n",
    "    no_face_frames = 0\n",
    "    previous_box = None\n",
    "\n",
    "    # Reset command stabilizer for a new run.\n",
    "    global _pending_direction, _pending_count, _stable_direction\n",
    "    _pending_direction = None\n",
    "    _pending_count = 0\n",
    "    _stable_direction = \"stop\"\n",
    "\n",
    "    try:\n",
    "        while True:\n",
    "            ok, frame = cap.read()\n",
    "            if not ok:\n",
    "                print(\"Frame read failed, retrying...\")\n",
    "                time.sleep(0.1)\n",
    "                continue\n",
    "\n",
    "            frame_h, frame_w = frame.shape[:2]\n",
    "\n",
    "            # MediaPipe Face Detection requires RGB.\n",
    "            rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "            results = face_detector.process(rgb)\n",
    "\n",
    "            chosen = None\n",
    "            if results.detections:\n",
    "                chosen = choose_largest_face(results.detections, frame_w, frame_h)\n",
    "\n",
    "            if chosen is not None:\n",
    "                no_face_frames = 0\n",
    "                _area, confidence, raw_box, _detection = chosen\n",
    "\n",
    "                # Smooth only the selected face, not all detections.\n",
    "                face_box = smooth_box(previous_box, raw_box)\n",
    "                previous_box = face_box\n",
    "\n",
    "                candidate_direction = decide_direction(face_box, frame_w, frame_h)\n",
    "                direction = stabilize_direction(candidate_direction)\n",
    "                send_direction(direction)\n",
    "\n",
    "                x, y, w, h = face_box\n",
    "                face_center_x = x + w / 2.0\n",
    "                offset = (face_center_x - frame_w / 2.0) / frame_w\n",
    "\n",
    "                if show_window:\n",
    "                    # Face box\n",
    "                    cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)\n",
    "\n",
    "                    # Frame center and face center\n",
    "                    cv2.line(\n",
    "                        frame,\n",
    "                        (frame_w // 2, 0),\n",
    "                        (frame_w // 2, frame_h),\n",
    "                        (255, 0, 0),\n",
    "                        1,\n",
    "                    )\n",
    "                    cv2.circle(\n",
    "                        frame,\n",
    "                        (int(face_center_x), int(y + h / 2.0)),\n",
    "                        5,\n",
    "                        (0, 0, 255),\n",
    "                        -1,\n",
    "                    )\n",
    "\n",
    "                    cv2.putText(\n",
    "                        frame,\n",
    "                        f\"{direction.upper()}  conf:{confidence:.2f}\",\n",
    "                        (x, max(25, y - 10)),\n",
    "                        cv2.FONT_HERSHEY_SIMPLEX,\n",
    "                        0.65,\n",
    "                        (0, 255, 0),\n",
    "                        2,\n",
    "                    )\n",
    "                    cv2.putText(\n",
    "                        frame,\n",
    "                        f\"offset:{offset:+.2f} size:{w/frame_w:.2f}\",\n",
    "                        (10, 25),\n",
    "                        cv2.FONT_HERSHEY_SIMPLEX,\n",
    "                        0.6,\n",
    "                        (255, 255, 255),\n",
    "                        2,\n",
    "                    )\n",
    "\n",
    "            else:\n",
    "                no_face_frames += 1\n",
    "                # Don't immediately stop for a single missed frame.\n",
    "                if no_face_frames > NO_FACE_STOP_FRAMES:\n",
    "                    previous_box = None\n",
    "                    direction = stabilize_direction(\"stop\")\n",
    "                    send_direction(\"stop\")\n",
    "\n",
    "                if show_window:\n",
    "                    cv2.putText(\n",
    "                        frame,\n",
    "                        \"NO FACE\",\n",
    "                        (10, 30),\n",
    "                        cv2.FONT_HERSHEY_SIMPLEX,\n",
    "                        0.8,\n",
    "                        (0, 0, 255),\n",
    "                        2,\n",
    "                    )\n",
    "\n",
    "            if show_window:\n",
    "                cv2.imshow(WINDOW_NAME, frame)\n",
    "                if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "                    break\n",
    "\n",
    "            if max_seconds is not None and (time.time() - start_time) > max_seconds:\n",
    "                break\n",
    "\n",
    "    finally:\n",
    "        # Safety stop whenever the Python loop exits.\n",
    "        send_direction(\"stop\")\n",
    "        cap.release()\n",
    "        if show_window:\n",
    "            cv2.destroyAllWindows()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==================== RUN ====================\n",
    "# Start the face follower.\n",
    "# Press Q in the OpenCV window to stop.\n",
    "run_face_follower(show_window=True)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## V2 notes\n",
    "\n",
    "- The ESP32-CAM is unchanged at the protocol level: Python still sends `/motor?dir=forward|backward|left|right|stop`.\n",
    "- MediaPipe returns normalized face bounding boxes, which are converted to the same `(x, y, w, h)` format used by the original `decide_direction()` logic.\n",
    "- The largest face is still selected, preserving the original behavior when multiple faces are visible.\n",
    "- A simple exponential moving average smooths the selected face box, and two-frame command confirmation reduces rapid LEFT/RIGHT command changes.\n",
    "- The robot still performs full-speed pivot turns because the original Arduino wiring has ENA and ENB tied directly to 5V. PWM/proportional steering is a separate hardware/control upgrade.\n",
    "- If the ESP32 stream itself is unstable, MediaPipe cannot fix that network/video problem; verify the stream URL first.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
